#############################################################################
# Makefile for building: meego-app-tasks
# Generated by qmake (2.01a) (Qt 4.8.4) on: ?? ??? 4 20:11:26 2013
# Project:  meego-app-tasks.pro
# Template: subdirs
# Command: /usr/bin/qmake QTDIR=/usr/lib64 QMAKE=/usr/bin/qmake QMAKE_AR=x86_64-pc-linux-gnu-ar\ cqs QMAKE_CC=x86_64-pc-linux-gnu-gcc QMAKE_CXX=x86_64-pc-linux-gnu-g++ QMAKE_LINK=x86_64-pc-linux-gnu-g++ QMAKE_LINK_C=x86_64-pc-linux-gnu-gcc QMAKE_OBJCOPY=x86_64-pc-linux-gnu-objcopy QMAKE_RANLIB= QMAKE_STRIP= QMAKE_CFLAGS=-march=k8\ -O3\ -pipe\ -fomit-frame-pointer\ -msse\ -msse2\ -mmmx\ -m3dnow\ -msse4a QMAKE_CFLAGS_RELEASE= QMAKE_CFLAGS_DEBUG= QMAKE_CXXFLAGS=-march=k8\ -O3\ -pipe\ -fomit-frame-pointer\ -msse\ -msse2\ -mmmx\ -m3dnow\ -msse4a QMAKE_CXXFLAGS_RELEASE= QMAKE_CXXFLAGS_DEBUG= QMAKE_LFLAGS=-Wl,-O1\ -Wl,--as-needed QMAKE_LFLAGS_RELEASE= QMAKE_LFLAGS_DEBUG= QMAKE_LIBDIR_QT=/usr/lib64/qt4 QMAKE_LIBDIR_X11=/usr/lib64 QMAKE_LIBDIR_OPENGL=/usr/lib64 -o Makefile meego-app-tasks.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-model

model/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) model/ || $(MKDIR) model/ 
	cd model/ && $(QMAKE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/model/model.pro QTDIR=/usr/lib64 QMAKE=/usr/bin/qmake QMAKE_AR=x86_64-pc-linux-gnu-ar\ cqs QMAKE_CC=x86_64-pc-linux-gnu-gcc QMAKE_CXX=x86_64-pc-linux-gnu-g++ QMAKE_LINK=x86_64-pc-linux-gnu-g++ QMAKE_LINK_C=x86_64-pc-linux-gnu-gcc QMAKE_OBJCOPY=x86_64-pc-linux-gnu-objcopy QMAKE_RANLIB= QMAKE_STRIP= QMAKE_CFLAGS=-march=k8\ -O3\ -pipe\ -fomit-frame-pointer\ -msse\ -msse2\ -mmmx\ -m3dnow\ -msse4a QMAKE_CFLAGS_RELEASE= QMAKE_CFLAGS_DEBUG= QMAKE_CXXFLAGS=-march=k8\ -O3\ -pipe\ -fomit-frame-pointer\ -msse\ -msse2\ -mmmx\ -m3dnow\ -msse4a QMAKE_CXXFLAGS_RELEASE= QMAKE_CXXFLAGS_DEBUG= QMAKE_LFLAGS=-Wl,-O1\ -Wl,--as-needed QMAKE_LFLAGS_RELEASE= QMAKE_LFLAGS_DEBUG= QMAKE_LIBDIR_QT=/usr/lib64/qt4 QMAKE_LIBDIR_X11=/usr/lib64 QMAKE_LIBDIR_OPENGL=/usr/lib64 -o $(MAKEFILE)
sub-model-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) model/ || $(MKDIR) model/ 
	cd model/ && $(QMAKE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/model/model.pro QTDIR=/usr/lib64 QMAKE=/usr/bin/qmake QMAKE_AR=x86_64-pc-linux-gnu-ar\ cqs QMAKE_CC=x86_64-pc-linux-gnu-gcc QMAKE_CXX=x86_64-pc-linux-gnu-g++ QMAKE_LINK=x86_64-pc-linux-gnu-g++ QMAKE_LINK_C=x86_64-pc-linux-gnu-gcc QMAKE_OBJCOPY=x86_64-pc-linux-gnu-objcopy QMAKE_RANLIB= QMAKE_STRIP= QMAKE_CFLAGS=-march=k8\ -O3\ -pipe\ -fomit-frame-pointer\ -msse\ -msse2\ -mmmx\ -m3dnow\ -msse4a QMAKE_CFLAGS_RELEASE= QMAKE_CFLAGS_DEBUG= QMAKE_CXXFLAGS=-march=k8\ -O3\ -pipe\ -fomit-frame-pointer\ -msse\ -msse2\ -mmmx\ -m3dnow\ -msse4a QMAKE_CXXFLAGS_RELEASE= QMAKE_CXXFLAGS_DEBUG= QMAKE_LFLAGS=-Wl,-O1\ -Wl,--as-needed QMAKE_LFLAGS_RELEASE= QMAKE_LFLAGS_DEBUG= QMAKE_LIBDIR_QT=/usr/lib64/qt4 QMAKE_LIBDIR_X11=/usr/lib64 QMAKE_LIBDIR_OPENGL=/usr/lib64 -o $(MAKEFILE)
sub-model: model/$(MAKEFILE) FORCE
	cd model/ && $(MAKE) -f $(MAKEFILE)
sub-model-make_default: model/$(MAKEFILE) FORCE
	cd model/ && $(MAKE) -f $(MAKEFILE) 
sub-model-make_first: model/$(MAKEFILE) FORCE
	cd model/ && $(MAKE) -f $(MAKEFILE) first
sub-model-all: model/$(MAKEFILE) FORCE
	cd model/ && $(MAKE) -f $(MAKEFILE) all
sub-model-clean: model/$(MAKEFILE) FORCE
	cd model/ && $(MAKE) -f $(MAKEFILE) clean
sub-model-distclean: model/$(MAKEFILE) FORCE
	cd model/ && $(MAKE) -f $(MAKEFILE) distclean
sub-model-install_subtargets: model/$(MAKEFILE) FORCE
	cd model/ && $(MAKE) -f $(MAKEFILE) install
sub-model-uninstall_subtargets: model/$(MAKEFILE) FORCE
	cd model/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: meego-app-tasks.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) QTDIR=/usr/lib64 QMAKE=/usr/bin/qmake QMAKE_AR=x86_64-pc-linux-gnu-ar\ cqs QMAKE_CC=x86_64-pc-linux-gnu-gcc QMAKE_CXX=x86_64-pc-linux-gnu-g++ QMAKE_LINK=x86_64-pc-linux-gnu-g++ QMAKE_LINK_C=x86_64-pc-linux-gnu-gcc QMAKE_OBJCOPY=x86_64-pc-linux-gnu-objcopy QMAKE_RANLIB= QMAKE_STRIP= QMAKE_CFLAGS=-march=k8\ -O3\ -pipe\ -fomit-frame-pointer\ -msse\ -msse2\ -mmmx\ -m3dnow\ -msse4a QMAKE_CFLAGS_RELEASE= QMAKE_CFLAGS_DEBUG= QMAKE_CXXFLAGS=-march=k8\ -O3\ -pipe\ -fomit-frame-pointer\ -msse\ -msse2\ -mmmx\ -m3dnow\ -msse4a QMAKE_CXXFLAGS_RELEASE= QMAKE_CXXFLAGS_DEBUG= QMAKE_LFLAGS=-Wl,-O1\ -Wl,--as-needed QMAKE_LFLAGS_RELEASE= QMAKE_LFLAGS_DEBUG= QMAKE_LIBDIR_QT=/usr/lib64/qt4 QMAKE_LIBDIR_X11=/usr/lib64 QMAKE_LIBDIR_OPENGL=/usr/lib64 -o Makefile meego-app-tasks.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) QTDIR=/usr/lib64 QMAKE=/usr/bin/qmake QMAKE_AR=x86_64-pc-linux-gnu-ar\ cqs QMAKE_CC=x86_64-pc-linux-gnu-gcc QMAKE_CXX=x86_64-pc-linux-gnu-g++ QMAKE_LINK=x86_64-pc-linux-gnu-g++ QMAKE_LINK_C=x86_64-pc-linux-gnu-gcc QMAKE_OBJCOPY=x86_64-pc-linux-gnu-objcopy QMAKE_RANLIB= QMAKE_STRIP= QMAKE_CFLAGS=-march=k8\ -O3\ -pipe\ -fomit-frame-pointer\ -msse\ -msse2\ -mmmx\ -m3dnow\ -msse4a QMAKE_CFLAGS_RELEASE= QMAKE_CFLAGS_DEBUG= QMAKE_CXXFLAGS=-march=k8\ -O3\ -pipe\ -fomit-frame-pointer\ -msse\ -msse2\ -mmmx\ -m3dnow\ -msse4a QMAKE_CXXFLAGS_RELEASE= QMAKE_CXXFLAGS_DEBUG= QMAKE_LFLAGS=-Wl,-O1\ -Wl,--as-needed QMAKE_LFLAGS_RELEASE= QMAKE_LFLAGS_DEBUG= QMAKE_LIBDIR_QT=/usr/lib64/qt4 QMAKE_LIBDIR_X11=/usr/lib64 QMAKE_LIBDIR_OPENGL=/usr/lib64 -o Makefile meego-app-tasks.pro

qmake_all: sub-model-qmake_all FORCE

make_default: sub-model-make_default FORCE
make_first: sub-model-make_first FORCE
all: sub-model-all FORCE
clean: sub-model-clean FORCE
distclean: sub-model-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-model-install_subtargets FORCE
uninstall_subtargets: sub-model-uninstall_subtargets FORCE

dist:
	rm -fR meego-app-tasks-0.2.8 && git clone . meego-app-tasks-0.2.8 && rm -fR meego-app-tasks-0.2.8/.git && rm -f meego-app-tasks-0.2.8/.gitignore && mkdir -p meego-app-tasks-0.2.8/ts && lupdate *.qml model/*.cpp model/*.h -ts meego-app-tasks-0.2.8/ts/meego-app-tasks.ts && tar jcpf meego-app-tasks-0.2.8.tar.bz2 meego-app-tasks-0.2.8 && rm -fR meego-app-tasks-0.2.8 && echo; echo Created meego-app-tasks-0.2.8.tar.bz2

sub-model-check: model/$(MAKEFILE)
	cd model/ && $(MAKE) -f $(MAKEFILE) check
check: sub-model-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install_qmlfiles: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/meego-app-tasks/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/meego-app-tasks/ 
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/Action.qml $(INSTALL_ROOT)/usr/share/meego-app-tasks/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/BottomBar.qml $(INSTALL_ROOT)/usr/share/meego-app-tasks/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/CategoryItem.qml $(INSTALL_ROOT)/usr/share/meego-app-tasks/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/CategoryView.qml $(INSTALL_ROOT)/usr/share/meego-app-tasks/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/Checkbox.qml $(INSTALL_ROOT)/usr/share/meego-app-tasks/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/CreateNewTaskRow.qml $(INSTALL_ROOT)/usr/share/meego-app-tasks/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/main.qml $(INSTALL_ROOT)/usr/share/meego-app-tasks/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/TaskListPicker.qml $(INSTALL_ROOT)/usr/share/meego-app-tasks/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/TaskListView.qml $(INSTALL_ROOT)/usr/share/meego-app-tasks/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-tasks-0.2.8/work/meego-app-tasks-0.2.8/TasksDetailMenu.qml $(INSTALL_ROOT)/usr/share/meego-app-tasks/


uninstall_qmlfiles:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-tasks/Action.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-tasks/BottomBar.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-tasks/CategoryItem.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-tasks/CategoryView.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-tasks/Checkbox.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-tasks/CreateNewTaskRow.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-tasks/main.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-tasks/TaskListPicker.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-tasks/TaskListView.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-tasks/TasksDetailMenu.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/meego-app-tasks/ 


install: install_subtargets install_qmlfiles  FORCE

uninstall: uninstall_qmlfiles  uninstall_subtargets FORCE

FORCE:

